# SPDX-License-Identifier: GPL-2.0-or-later

xone-y := bus.o protocol.o auth.o crypto.o common.o
xone-wired-y := wired.o

obj-$(CONFIG_JOYSTICK_XONE) += xone.o
obj-$(CONFIG_JOYSTICK_XONE_WIRED) += xone-wired.o
