# SPDX-License-Identifier: GPL-2.0-or-later

xone-y := bus.o protocol.o auth.o crypto.o common.o
xone-wired-y := wired.o
xone-gip-gamepad-y := gamepad.o
xone-gip-chatpad-y := chatpad.o
xone-gip-headset-y := headset.o

obj-$(CONFIG_JOYSTICK_XONE) += xone.o
obj-$(CONFIG_JOYSTICK_XONE_WIRED) += xone-wired.o
obj-$(CONFIG_JOYSTICK_XONE_GIP_GAMEPAD) += xone-gip-gamepad.o
obj-$(CONFIG_JOYSTICK_XONE_GIP_CHATPAD) += xone-gip-chatpad.o
obj-$(CONFIG_JOYSTICK_XONE_GIP_HEADSET) += xone-gip-headset.o
